CREATE TABLE IF NOT EXISTS datasets (id TEXT PRIMARY KEY, name TEXT NOT NULL, crs TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS dataset_versions (id TEXT PRIMARY KEY, dataset_id TEXT NOT NULL REFERENCES datasets(id), status TEXT NOT NULL, input_hash TEXT NOT NULL, manifest_hash TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS build_jobs (id TEXT PRIMARY KEY, version_id TEXT NOT NULL, status TEXT NOT NULL, input_hash TEXT NOT NULL, output_hash TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '');
